import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-teal-700 flex justify-around items-center h-14">
          <Link href={"/Articles"}>
            <button className="border border-solid border-white bg-slate-700 p-2 rounded-3xl text-white">
              To articles
            </button>
          </Link>

          <Link href={"/"}>
            <button className="border border-solid border-white bg-slate-700 p-2 rounded-3xl text-white">
              To Home
            </button>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
